### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by IambecauseIthink** [wangsen99/FDLNet#1]
I could run `scripts/eval.py` smoothly, but when running `scripts/train.py`, it went wrong with "TypeError: 'NoneType' object is not callable
", could you please help me to figure out?

**Comment by wangsen99** [comment]
Our model needs `criterion` (loss function) during training, you should simply modify the `core/models/fdlnet_deeplab.py` following the [awesome-semantic-segmentation-pytorch"](https://github.com/Tramac/awesome-semantic-segmentation-pytorch) or modify the `scripts/train.py` .

**Comment by IambecauseIthink** [comment]
Thanks for your answer. I think the main difference in [`core/models/fdlnet_deeplab.py`](https://github.com/wangsen99/FDLNet/blob/main/core/models/fdlnet_deeplab.py#L48-L49) is:
   ` if self.training:
            return self.criterion(outputs, gts)` than other models in [awesome-semantic-segmentation-pytorch](https://github.com/Tramac/awesome-semantic-segmentation-pytorch)
I tried to print `self.criterion` and `self.model.criterion` in [scripts/train.py](https://github.com/wangsen99/FDLNet/blob/main/scripts/train.py#L211):
`print(self.criterion) # The output is MixSoftmaxCrossEntropyLoss()
print(self.model.criterion) #The output is None`

I don't know how to modify it, and just simply removed [this](https://github.com/wangsen99/FDLNet/blob/main/core/models/fdlnet_deeplab.py#L48-L49) and the init of the criterion in the class, then it can start training. I'm not sure how this will affect, could you please help?

**Comment by wangsen99** [comment]
You can just remove the `self.criterion` and use `MixSoftmaxCrossEntropyLoss()` to train your own model, but our paper uses a multi-loss to gain better performance. You can try to implement it. ^_^

**Comment by IambecauseIthink** [comment]
Thanks a lot!
