### ISSUE TITLE
关于cropsize的问题

### ISSUE THREAD

**Issue by MasterBeluga** [wangsen99/FDLNet#4]
您好读完实验部分，发现您对图片进行了[384，768]的裁剪操作，但是我在dataset没有发现您对图片的crop相关操作，只能看到设置cropsize为480，请问是您重写了_sync_transform（）函数吗？

**Comment by wangsen99** [comment]
你好，我们对数据加载时的随机裁剪函数进行了重写，将裁剪的大小变换为384*768

**Comment by MasterBeluga** [comment]
真心的祝贺你的论文被TIP录用！！！

**Comment by wangsen99** [comment]
谢谢！
