### ISSUE TITLE
About BDD100k-night dataset

### ISSUE THREAD

**Issue by swcdjack** [wangsen99/FDLNet#6]
Thank you for the open source of your paper, can you provide the BDD100k-night dataset mentioned in the paper? I can't find the download path. I don't know how to download the official website, I hope your answer

**Comment by wangsen99** [comment]
Hi, here is the link of the BDD100k-night dataset : [BDD100k-night](https://drive.google.com/file/d/1l4Mh3V7OcCbD6GpxPzovloLlRWSAZ4vZ/view?usp=share_link). 
Hope it will be useful for your research.

**Comment by swcdjack** [comment]
Thank you for your selfless help，and I found an interesting phenomenon that in the Nightcity validation set, your eval. py ran out of Miou (such as the highest I found, 55.7%) higher than what you wrote in your paper (54.6%). May I ask why the highest result was not included in the paper?

**Comment by wangsen99** [comment]
Hi, the calculation of mIOU is dynamically updated in the code, so for the entire test set, the result is 54.6%, and the others are only intermediate results.
