### ISSUE TITLE
About training details

### ISSUE THREAD

**Issue by sunzc-sunny** [wangsen99/FDLNet#7]
Hello, congratulations on your article is included in TIP. I am very interested in your work and hope to reproduce the result. However, since no training details are provided, I use train.py to train according to the parameters in your article, and the result is quite different from that in the article. I am worried that my reproduction method is wrong. If you could provide the full training code and details, I would be very grateful!

**Comment by Siyuexi** [comment]
*Same issues with Dr.Sun.

**Comment by wangsen99** [comment]
The training code has been released, sorry for the late reply QAQ.
